site_name: Daily Developing Guide
nav:
    - Home: index.md
    - Sub:
        - Detail: detail.md
        - Mkdocs: Tool\mkdocs.md
    - About: about.md
    - Airflow: airflow.md
    - Django: django.md
theme: material
