site_name: Daily Developing Guide
nav:
    - Home: index.md
    - Language:
        - Python: language/python.md
        - SQL: language/sql.md
        - Unix Commands & Bash: language/unix_commnads_bash.md

    #     - HTML
    #     - CSS
    #     - JS
        
    # - Client:
    #     - Web
    #     - Vue
    - Server:
        - Nginx: server/nginx.md
        - Supervisor: server/supervisor.md
        - Mkdocs: server/mkdocs.md
        - Django: server/django.md
        - Airflow: server/airflow.md
        # - Flask
        # - Gunrion
        # - Mongodb
        # - PostgreSQL
    # - Modeling:
    #     - Data preprocessing: modeling/dataPreprocessing.md
        # - Clusifiy
        # - Cluster 
        # - Utils
        # - SQL Calculation
        # - NLP
        # - Computer Vision
        # - Audio
    # - Tool:
    #     - Git
    #     - VScode
    
theme: 
  name: material
  palette:
    primary: 'Light Green'
    accent: 'pink'
  logo:
    icon: 'cloud'
  favicon: 'static/images/favicon.ico'
# repo_name: 'linqingbin.github.io'
# repo_url: 'https://github.com/linqingbin/linqingbin.github.io'

extra_css:
    - static/css/extra.css
